version: '3.8'

services:
  threatpathmapper:
    build:
      context: .
      dockerfile: Dockerfile.ssl-fix
    container_name: threatpathmapper-container
    volumes:
      # Mount entire data directory to ensure all unzipped files are accessible
      - ./data:/app/data
      # Mount tf_hub cache to persist model downloads
      - tf_hub_cache:/app/data/tf_hub
    environment:
      - TFHUB_CACHE_DIR=/app/data/tf_hub
      - TF_ENABLE_ONEDNN_OPTS=0
    stdin_open: true
    tty: true
    # Keep container running for interactive access
    command: tail -f /dev/null

volumes:
  tf_hub_cache: